name: get_user_region_from_ip
description: Gets the user's region from their IP address.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  http: ^1.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
