name: flutter-packages-monorepo

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    updateGitTagRefs: true

scripts:
  test:all:
    run: |
      melos run test --no-select
    description: |
      Run all tests available.
  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --no-pub"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
      ignore:
        - "*web*"
        - "*odm*"
        - "*example*"
