name: flutter_packages_monorepo

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.3.0"
dev_dependencies:
  melos: ^3.1.1

# Run in terminal: rps version
scripts:
  version: melos version --all # bump all packages
  bootstrap: melos bootstrap # install all dependencies