name: getx_provider
description: A starting point for Dart libraries or applications.
version: 1.0.3
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.3.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.3
test:
dependencies: { get: ^4.6.5 }
