name: connectivity_provider
description: A starting point for Dart libraries or applications.
version: 1.0.4
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.3
  test:
dependencies: {connectivity_plus: ^2.3.4, get: ^4.6.5}
