name: foodhero_models
description: Models for foodhero project.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.8
  cloud_firestore: ^4.15.3
  dev: ^1.0.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  google_maps_flutter: ^2.2.8
  intl: ^0.18.1
  json_annotation: ^4.8.1
  # path: ^1.8.0

dev_dependencies:
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0

scripts:
  # exampe: rps build
  build: dart run build_runner build --delete-conflicting-outputs

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
