name: firebase_crashlytics_provider
description: A starting point for Dart libraries or applications.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: { firebase_crashlytics: ^2.8.2 }
