name: firebase_crashlytics_provider
description: A starting point for Dart libraries or applications.
version: 1.0.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.3.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test:
dependencies: { firebase_crashlytics: ^3.4.2 }
