name: firebase_auth_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  firebase_auth: ^3.3.20
  google_sign_in: ^5.3.3
  sign_in_with_apple: ^3.1.0
  firebase_crashlytics_provider:
    git:
      url: https://github.com/Albertbol/flutter-packages-monorepo.git
      path: packages/firebase_crashlytics_provider
      ref: firebase_crashlytics_provider-v1.0.0
  connectivity_provider:
    git:
      url: https://github.com/Albertbol/flutter-packages-monorepo.git
      path: packages/connectivity_provider
      ref: connectivity_provider-v1.0.0
  getx_provider:
    git:
      url: https://github.com/Albertbol/flutter-packages-monorepo.git
      path: packages/getx_provider
      ref: getx_provider-v1.0.0
  crypto: ^3.0.2
  get: ^4.6.5
  mocktail: ^0.3.0
  flutter_facebook_auth: ^4.4.1+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
