name: firebase_auth_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  firebase_auth: ^3.3.20
  google_sign_in_ios:
    git:
      url: https://github.com/mono0926/plugins
      ref: fix-flutterfire
      path: packages/google_sign_in/google_sign_in_ios
  sign_in_with_apple: ^4.0.0
  firebase_crashlytics_provider:
    git:
      url: https://github.com/Albertbol/flutter-packages-monorepo.git
      path: packages/firebase_crashlytics_provider
  connectivity_provider:
    git:
      url: https://github.com/Albertbol/flutter-packages-monorepo.git
      path: packages/connectivity_provider
  getx_provider:
    git:
      url: https://github.com/Albertbol/flutter-packages-monorepo.git
      path: packages/getx_provider
  crypto: ^3.0.2
  get: ^4.6.5
  mocktail: ^0.3.0
  flutter_facebook_auth: ^4.3.4+2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
