name: firebase_auth_provider
description: A starting point for Dart libraries or applications.
version: 1.1.2
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  firebase_auth: ^4.12.0
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  firebase_crashlytics_provider:
    git:
      url: https://github.com/Albertbol/flutter-packages-monorepo.git
      path: packages/firebase_crashlytics_provider
      ref: firebase_crashlytics_provider-v1.0.1
  connectivity_provider:
    git:
      url: https://github.com/Albertbol/flutter-packages-monorepo.git
      path: packages/connectivity_provider
      ref: connectivity_provider-v1.0.2
  getx_provider:
    git:
      url: https://github.com/Albertbol/flutter-packages-monorepo.git
      path: packages/getx_provider
      ref: getx_provider-v1.0.1
  crypto: ^3.0.3
  get: ^4.6.6
  mocktail: ^1.0.1
  flutter_facebook_auth: ^6.0.2

dev_dependencies:
  test:
