name: fire_auth_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  firebase_auth: ^3.3.20
  google_sign_in: ^5.3.3
  sign_in_with_apple: ^4.0.0
  firebase_crashlytics_provider:
    git:
      url: https://github.com/Albertbol/flutter-packages-monorepo.git
      path: packages/fire_crashlytics_provider

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
